version: '3.8'
services:
  db:
    image: postgres:15
    container_name: starwars_db
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: starwars
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
